export const ADD_THE_CATEGORY = "ADD_THE_CATEGORY";
export const DELETE_THE_CATEGORY = "DELETE_THE_CATEGORY";

export const ADD_THE_PRODUCT = "ADD_THE_PRODUCT";
export const DELETE_THE_PRODUCT = "DELETE_THE_PRODUCT";

export const ADD_PRODUCT_TO_THE_BASKET = "ADD_PRODUCT_TO_THE_BASKET";
export const INCREASE_QTY_TO_BASKET_PRODUCT = "INCREASE_QTY_TO_BASKET_PRODUCT";
export const CLEAR_THE_BASKET = "CLEAR_THE_BASKET";

export const SET_LANGUAGE = "SET_LANGUAGE";


export const OPEN_SUCCESS_MODAL = 'OPEN_SUCCESS_MODAL'
export const CLOSE_SUCCESS_MODAL = 'CLOSE_SUCCESS_MODAL'
